spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 1q2w3e4r!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath*:ddl/schema.sql
logging:
  level:
    org.hibernate.SQL: debug