DROP TABLE IF EXISTS HOST;

CREATE TABLE HOST (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    IP VARCHAR(255),
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_ALIVE BOOLEAN NOT NULL DEFAULT 1,
    IS_LAST_ALIVE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY name_unique(NAME),
    UNIQUE KEY ip_unique(IP)
);